nginx:
    build: ./nginx
    ports:
        - "80:80"
    links:
        - "php"
    volumes_from:
        - php

php:
    image: yangdesheng/php56
    ports:
        - "9000:9000"
    volumes:
        - ~/PHP/jobtong/branches/yangdesheng:/opt/www
