FROM php:5.4-fpm

ADD sources.list /etc/apt/sources.list

# Install general utilities
RUN apt-get update \
    && apt-get install -y \
        vim \
        net-tools \
        procps \
        telnet \
        netcat \
    && rm -r /var/lib/apt/lists/*

# Install utilities used by TYPO3 CMS / Flow / Neos
RUN apt-get update \
    && apt-get install -y \
        imagemagick \
        graphicsmagick \
        zip \
        unzip \
        wget \
        curl \
        git \
        mysql-client \
        moreutils \
        dnsutils \
    && rm -rf /var/lib/apt/lists/*

# gd
RUN buildRequirements="libpng12-dev libjpeg-dev libfreetype6-dev" \
    && apt-get update && apt-get install -y ${buildRequirements} \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/lib \
    && docker-php-ext-install gd \
    && apt-get purge -y ${buildRequirements} \
    && rm -rf /var/lib/apt/lists/*

# pdo_mysql
RUN docker-php-ext-install pdo_mysql

# mysqli
RUN docker-php-ext-install mysqli

# mysql
RUN docker-php-ext-install mysql

# mcrypt
RUN runtimeRequirements="re2c libmcrypt-dev" \
    && apt-get update && apt-get install -y ${runtimeRequirements} \
    && docker-php-ext-install mcrypt \
    && rm -rf /var/lib/apt/lists/*

# mbstring
RUN docker-php-ext-install mbstring

#RUN apt-get update && apt-get install -y \
#        libmcrypt-dev \
#        # libfreetype6-dev \
#        # libjpeg62-turbo-dev \
#        # libpng12-dev \
#        && rm -r /var/lib/apt/lists/*

# RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
#     && docker-php-ext-install zip \
#     && docker-php-ext-install gd \

#RUN docker-php-ext-install mcrypt \
#    && docker-php-ext-install mysqli \
#    && docker-php-ext-install mbstring

#    # && docker-php-ext-install opcache \
#    # && echo "zend_extension=opcache.so" >> "/usr/local/etc/php/conf.d/ext-opcache.ini" \
#    # && echo "opcache.enable_cli=1" >> "/usr/local/etc/php/conf.d/ext-opcache.ini" \
#    # && echo "opcache.memory_consumption=128" >> "/usr/local/etc/php/conf.d/ext-opcache.ini" \
#    # && echo "opcache.interned_strings_buffer=8" >> "/usr/local/etc/php/conf.d/ext-opcache.ini" \
#    # && echo "opcache.max_accelerated_files=4000" >> "/usr/local/etc/php/conf.d/ext-opcache.ini" \
#    # && echo "opcache.fast_shutdown=1" >> "/usr/local/etc/php/conf.d/ext-opcache.ini" 



VOLUME ["/var/www/html"]
EXPOSE 9000